### PR TITLE
Fix integrated dynamics Generator, mechanical squeezer, and Mechanical drying basin recipes

### PR DESCRIPTION
**Pull request by theboo**
Changed recipe to use batteries with 0 energy. ID made a recent change where all batteries have the energy level NBT(on previous versions an empty battery had no nbt data) making it no longer possible to use .anyDamage()... i tried for quite some time to make it work with all energy levels. I also tried to make it work with both empty and full, but short of adding multiple recipes i could not find a way. Maybe you will have better luck but this will at least make these items craftable 💃

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Thanks for your contribution :D 
Did you try with `<integrateddynamics:energy_battery>.withTag({})`?

**Comment by theboo** [comment]
trying without anything in the brackets? ill try right now!

**Comment by theboo** [comment]
tested `<integrateddynamics:energy_battery>.withTag({})` works perfect, made change to commit

**Comment by NillerMedDild** [comment]
Awesome, nice work, thanks again.

**Pull request merged**
