### PR TITLE
It's unnecessary to remove and re-add all exu2 generators.(use NBTMatch flag)

### PR DESCRIPTION
**Pull request by friendlyhj**
use recipes.remove(output, NBTMatch);
set NBTMatch true can remove the recipe of machine block, not other machines.

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
The problem is that with this removal, you are also removing the recipes for other XU tiles with the "machine" ID, most importantly, the XU furnace and crusher.

**Comment by friendlyhj** [comment]
Don't worry.Only the recipe of machine block with empty NBT will be removed.XU furnace and crusher aren't influenced.

**Comment by NillerMedDild** [comment]
Thanks for the PR! 

It looks good, but I'm not entirely sure that the recipes I readded aren't tweaked, so I have to double check before merging.

**Comment by friendlyhj** [comment]
Oops,there is a mistake. line 43 should have a true NBTMarch,too.

**Comment by NillerMedDild** [comment]
Thanks for your help!

**Pull request merged**
