### PR TITLE
Added link to hastebin to ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
Felt like that'd be a good idea.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Hastebin links have a tendency to die out, that's why we're not linking to it anymore :)
As for the added text, I don't think people who paste their crash logs actually pay attention to the template, so I think it would just add more noise tbh.

**Comment by MaxNeedsSnacks** [comment]
Ah yeah, I get that. Also... `true`

**Comment by MaxNeedsSnacks** [comment]
Just force-pushed to dev to revert the changes ^^

**Comment by NillerMedDild** [comment]
Thanks :)

**Pull request closed without merging**
