### PR TITLE
Blacklist Induction Cell stuff from BBW

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**

### CODE REVIEW

**Comment by MaxNeedsSnacks** [comment]
Playtested already, works just fine, and the wands that *can* still place Induction Cells respect their NBT data... semi-correctly

**Comment by NillerMedDild** [comment]
Semi-correctly? :P

**Comment by MaxNeedsSnacks** [comment]
well they ignore the NBT data when deciding what to place, but they do respect the nbt data of the blocks they're placing^^

**Comment by NillerMedDild** [comment]
Ah nice!

**Pull request merged**
