### PR TITLE
Fixed more minor issues

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
Title says it all, these commits close some of the rather minor issues that are currently still unresolved

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Good stuff :D

**Comment by MaxNeedsSnacks** [comment]
:+1: still hoping on getting the JETIF pull request merged today so that mod can be updated for 1.57 as well

**Comment by NillerMedDild** [comment]
1.57 won't be for a while, I'm busy atm :)

**Comment by MaxNeedsSnacks** [comment]
Still got plenty of time then ^^

**Pull request merged**
