### PR TITLE
Add Storage Cell Helper function

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
- Added a helper function to the script to overwrite default cell recipes.

This change both cleans up the AE2 script file a little bit and makes it easier for you to edit Storage Housing recipes in the future, should you desire to do so.

There are still some annotations in the file that you can review if you want to, I still need your feedback on one planned change. (search for "FIXME" and "TODO" tags)

### CODE REVIEW

**Comment by friendlyhj** [comment]
Custom function? That is a good idea.But are you sure "_i" and "_o" are valid value name?

**Comment by MaxNeedsSnacks** [comment]
They are valid names for parameters, but they can be changed to "i" and "o" or "input" and "output", of course. I just called them whatever really.

**Comment by friendlyhj** [comment]
I searched just now,yeah,they are vaild.(and I deleted my commet)But the way to call is a little strange.Custom function is good.I used it when creating new items,blocks,etc by contenttweaker.However,in this case,is a for loop better?

**Comment by MaxNeedsSnacks** [comment]
Oh yeah I could and should definitely use a loop over, say, an array to minify the file even further, but the problem is that you can't just go `for` with integers here since the AE2 cells all have unique IDs and don't just use incremental metadata.

(Also I am quite new to ZenScript so I don't really know how to use variables in bracket handlers)

**Comment by friendlyhj** [comment]
It looks like that you don't know array...

**Comment by MaxNeedsSnacks** [comment]
Oh know I do know arrays it's just that I'm a bit skeptical of for-each really being all that helpful here. I could still implement it, though, hold up.

**Comment by MaxNeedsSnacks** [comment]
Reminder to self: Don't just replace stuff with Ctrl+F... whoops!

**Comment by NillerMedDild** [comment]
Thank you for your hard work, it looks good :) I've looked it over and it looks solid, I need to give it a once-over in-game too though.

**Comment by NillerMedDild** [comment]
In regards to the `TODO`, I think a helper function for high tier storage components would be nice aswell, but I'll just make that since I closed the PR :P

**Comment by NillerMedDild** [comment]
FYI, calling an array `recipes` is a terrible idea.

**Comment by MaxNeedsSnacks** [comment]
Ah yup, whoops, it's supposed to be a reserved keyword and I simply... forgot about that.

Should've called it cellRecipes like I intended to

**Comment by NillerMedDild** [comment]
That's exactly what I renamed it :P

**Pull request merged**
