### PR TITLE
Update Ice & Fire to version 1.8.1

### LINKED ISSUE #1334: Ice and Fire 1.8 adds lots of new content
**Modpack version**
1.68 I hope?

**Can the issue be reproduced?**
n/a

**Issue**
Just wanted to give you a heads-up that Ice and Fire 1.8 adds a lot of new stuff and will probably need a few tweaks to the `IceAndFire.zs` script (new armor etc).

Thank you so much for continuing to keep this modpack up to date after all this time.

### PR DESCRIPTION
**Pull request by Ricket**
Fixes #1334 

@NillerMedDild On all of the below, of course feel free to comment / disagree / fix / revert. This is my first time officially doing a mod update for a modpack but I've been running packs & servers for years. Now for the thorough explanation of these changes:

Updated ice_and_fire.cfg by just running with 1.8.1. The "Amphithere Spawn Weight" has had its default lowered so I lowered the setting to match. There is a new setting to whitelist dimensions where miscellaneous structures are generated; not sure if the dimensions 101-122 should be added to match the "Whitelisted Dragon Dimensions" setting.

The dragon cave loot tables have split to male/female so I updated the LootTweaker file. Didn't touch the list of files. The loot tables do differ slightly male vs female (male has a few more loot) but I think it's probably fine to add the full set of modpack rewards to both. The cyclops cave is the same, and no other loot tables were added.

LootTableTweaker.zs has lines to remove the silver metal armor from loot tables, that's fine. No additional metal armor was added.

Testing: crafttweaker.log has no errors. Also, found a dragon nest and confirmed the chests had cool stuff in them.

I removed the new fire/ice dragonsteel tools. Tinker's materials exist which have basically the same special effects. I also additionally removed the myrmex tools, which existed in 1.7.1 but I think was an oversight -- these also have tinker's tool materials. I left the myrmex stinger swords and staffs, and I left the dragonsteel armors.

There are various new weapons which are crafted with rare drops from various iceandfire animals, they have special effects and I think it's right to leave them alone. (this is things like Hippocampus Slapper, Stamphalian Bird Dagger, Tide Trident, Siren Flute, Hippogryph Talon Sword..)

Testing: saw that the items aren't in JEI. (I compared JEI screenshots from 1.7.1 vs 1.8.1 to find new items, and also diffed item and entity dump csvs)

I updated the cyclic monster ball blacklist. Tried to check whether something extends EntityLiving, so I left off the various arrows and fireball-type projectiles. Also alphabetized it. Copied the new list to morbs.cfg.

Testing: tried the monster ball on various things e.g. skulls

I blacklisted the ice&fire skulls in Neat's config -- doesn't make any sense to show health bars above them. Testing: confirmed that now they don't have any health bars.

`betterquesting/DefaultLoot.json` has only green fire dragon egg; there doesn't seem to be a functional difference between the dragon colors that I could find (e.g. their armors all have the same armor value), should it have all 8? I didn't want to add the other 7 and cause dragon eggs to be 8x the chance though. Not sure how to edit this. At the very least I feel like it should have an ice dragon egg added to it.

`enderio/recipes/spawner` had `iceandfire:icevillager` but that's not a valid entity, the entity is `iceandfire:snowvillager`. Strange thing is the ice&fire github history doesn't seem to show the villager ever being called `icevillager` and no search results for it in the current HEAD. Additionally I don't really understand what this file is doing, other than setting spawn cost multipliers for the entities. Hopefully this was the right fix to make, or maybe we should revert it. Especially since I didn't test it (not sure how).

Updated the forestry backpacks where it seemed to make sense. Especially the hunter backpack with all the new mob drops (a couple already existed in 1.7.1). Fixed spelling of "leather". But the spelling of "tongue" is typoed in the item ID so that one is on purpose. Testing: spawned in all the various entity items and confirmed when I pick them up they go into the hunter bag.

There are a few auto-updating configs that I didn't include in this PR because I didn't want to clutter it with the auto generated junk.

Edit -- worth noting that I only did the testing mentioned above as I worked on these files. I have not just casually played while having these changes (I only just finished working on them) and have not had other players test them either. So it's probably worth letting it soak on the test server for a bit before updating the pack... In case I missed something, or in case 1.8.1 performance is bad for example.

### CODE REVIEW

**Comment by Ricket** [comment]
Bonus screenshot of JEI; red crossed-out are items that existed in 1.7.1; circled things are new; orange crossed-out are ones I deleted via crafttweaker.

image

**Comment by Frikkle** [comment]
Thank you for doing this work and writing such an elaborate report in your PR.

One question I have: does the update change world generation related stuff? If so it would cause the update to be backwards incompatible with existing worlds without getting weird generation glitches.

**Comment by NillerMedDild** [comment]
Great work! Frikkle, could you be persuaded into using this PR with your server, and updating Ice&Fire to test performance/worldgen?

**Comment by Frikkle** [comment]
I'll have a go at it today or tomorrow, depending on when my work load permits it. I'll get back here when I start the tests.

**Comment by NillerMedDild** [comment]
Thanks! I'll start SP testing now.

**Comment by Ricket** [comment]
Thanks guys. There are new worldgen classes added for a dragon roost, and changes to the dragon dens (caves). But surprisingly, I created a world on a fresh Twitch 1.68 pack creation and sat at spawn for a minute to let things generate, then exited and applied the changes in this PR (plus the 1.8.1 mod jar itself) and loaded the same world, and I flew around in all directions and did not see any of the worldgen cliffs. So I think it's ok..? Maybe because it's only new structures and not new land generation?

**Comment by NillerMedDild** [comment]
Makes sense, thanks for checking :D

**Pull request merged**
