### PR TITLE
Add tinkers construct beginner quest

### LINKED ISSUE #1921: It would be nice to have a quest to make your first Tinkers' Construct Tool
**Modpack version**
1.82a

**Issue**
Having set up a new server again recently, including some experienced and new players, we noticed there isn't actually a quest to guide new players through how to make tinker's construct tools. I find this to be the number one hurdle new players have to overcome before getting any enjoyment out of expert modpacks like these. Therefore I suggest adding a quest to the Getting Started questline.

One might argue that beginners should start by playing the normal Enigmatica 2 modpack, but more advanced players also enjoy playing with friends, and getting them into this modpack we have found on my server that this is the number one thing we keep teaching new players.

I'll open a pull request with my first draft of what it might look like

### PR DESCRIPTION
**Pull request by tweelix**
resolves #1921. 

Adds two new quests to the Getting Started quest line.
One to make the Tinkers' basic workbenches, the second (optional) to create a wooden pickaxe.

Let me know if I've done anything wrong with editing the quest book, or any other changes I should make.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Thank you for contributing, but I'm afraid I can't accept it - There are way too many changes in that file considering you only added two quests. If you can somehow clean that up, I'll gladly re-review :)

**Comment by tweelix** [comment]
The reason for the large diff is that BetterQuesting seems to increment every quest ID whenever I add a quest earlier on. I'll try some more experimenting with manually editing the JSON but so far have had no luck.

**Comment by NillerMedDild** [comment]
Hmm..

**Comment by NillerMedDild** [comment]
Could you perhaps provide the details of the quests in text here instead? Then I'll add them myself at some point and credit you :)

**Comment by tweelix** [comment]
No Worries, honestly there is probably a way to do it that I just don't know about. I've tried many different combinations of manually adding them to the json file with their own id's but as soon as I then move them in the editor they just change everything again.

Screenshots and text below:

**Tools**
```
Vanilla Pickaxes don't work, your first Tools will need to be Tinkers' Construct Tools made in the Tool Station.

However first you will need to make patterns in the Stencil Table, and parts for your tools in the Part Builder.

(Hint: You can place all of these workbenches next to each other to access all of them at once in the UI)
```

**Your First Pickaxe**
```
Now use the Part builder to build parts for your pickaxe out of wood.
These can then be made into a working Pickaxe using the Tool Station
```

PickaxeQuest
Newquests
questline

**Pull request closed without merging**
