### PR TITLE
Is now possible to disable channels on AE2

### PR DESCRIPTION
**Pull request by thakyZ**
I have made changes that check to see if the ME Controller exists, because if the Channels are disabled on the server side, player's cannot join.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Looks good to me! I'll test it and include it in the next update if nothing explodes.

Thank you for your contribution! It's gonna benefit a lot of people I think.

**Comment by Nemo4evr** [comment]
From someone that truly loathes the channel system of AE2 . . . my most sincere GRATITUDE !  THANK YOU!  THANK YOU!  THANK YOU!

**Comment by Tntdruid** [comment]
How do play whit no channels in AE2?

**Comment by NillerMedDild** [comment]
You disable channels in the AE2 config :)

**Comment by Tntdruid** [comment]
I did that :)

Some recipes still need the ME Controller, does not show up in jei.

**Comment by NillerMedDild** [comment]
Which modpack version are you on?

**Comment by Tntdruid** [comment]
1.76a

**Comment by NillerMedDild** [comment]
Server or single player?

**Comment by Tntdruid** [comment]
single player

**Comment by NillerMedDild** [comment]
Alright :/ are you getting error messages printed in chat when you log in?

**Comment by Tntdruid** [comment]
Before i see:

Missing minecraft:blocks:
appliedenergistics2:controller

**Comment by NillerMedDild** [comment]
Alright, and the issue you get?

**Comment by Tntdruid** [comment]
Last time i played the pack appliedenergistics2:controller was used in recipes.

**Comment by NillerMedDild** [comment]
Was that before or after the config change?

**Comment by Tntdruid** [comment]
I used a old world whit channels, made a backup first :)

**Comment by NillerMedDild** [comment]
Soo is the issue still present, after you restarted?

**Comment by Tntdruid** [comment]
No only first load.

**Comment by NillerMedDild** [comment]
So there's no issue xD alright

**Pull request merged**
