### PR TITLE
🐝 Bee rework

### PR DESCRIPTION
**Pull request by Krutoy242**
Bee breeding example

The bees in E2E require big changes.  
They work too slowly and give out very poor resources.

Players never use them, except for .

This *Pull Request* is a collection of radical changes to bees, including 16 new species that can be useful until the very end of the game.

As with my [previous PR](https://github.com/NillerMedDild/Enigmatica2Expert/pull/1926), code may contain non-working code - it will be refined if the changes are confirmed.

-----------------------------------
-----------------------------------

- Recipes and machines changes
  -  can melt some items in 
    > Melts   
  -  produce more  and 
  -  output more 
  -  and  WAY cheaper
    > Its feels too grindy for so low value. Alviery practically increase only produce speed.
      > 
- **All Combs buffed**  
  Some combs produce additional modded items
  - -> 
  -  -> 
  -  -> 
  - [Cocoa Comb] -> 
  - [Powdery Comb] -> 
  - [Wheaten Comb] -> 
  - [Irradiated Comb] ->  + 
    > Note: *Irradiated* painly hard to automate - they destroying
    > all blocks around Apiary
- 16 new bee species with various output
  Some "speciality" output:
    > 
  **Speciality** is when bee working in its "native" biome.  
  Processing custom **Combs** and **Honey Drops** would give various items:
    > - ")  
    > Only High-Tier bees produce cool materials.  
    > Breed such bees would take 10-20 game hours.
- Gendustry fluids nerfs
  -  now crafted from some radioactive byproducts  instead of bare redstone
  -  made from raw prime animania meat instead of raw vanilla meat
    > This changes mostly not affect already working automation,
    > because Protein nor Mutagen used to any crafts except Gendustry machines
-  buff to encourage players to use it
- Reduce Ticks for Bee cycle (about -50%)

### CODE REVIEW

**Comment by ReiDaTecnologia** [comment]
Ye, bees most of the time is ignored until someone use an item from it to craft something else. Bees need to buffed for people to stop saying "Not the bees" and start saying "Yes, the bees!"

**Comment by NillerMedDild** [comment]
Is this finished? :)
I'd like the color bees re-added, but other than that this looks good 👍

**Comment by Krutoy242** [comment]
> Is this finished?

I would need all my PR's to be reviewed, because some changes intersect each other, so i would like to know what would be accepted and what would be rejected first. Then i could refine code.

> I'd like the color bees re-added

But why? They just barely litter JEI.

**Comment by NillerMedDild** [comment]
All approved :)

Because I think they're a fun way to automate dye, always using Botania or Mystical Agriculture is boring :P

**Comment by Krutoy242** [comment]
Force-pushed and ready to merge.

Tests passed and described at commit messages.

Only change from previous version is that Bee Ticks reduced up to `550` -> `300`.

**Comment by NillerMedDild** [comment]
> And, returned colored bees. Through, their meta-values changed, so if players had some colored honey/combs, they turned to

Fair enough, we'll need to mention that in the changelog 👍

**Pull request merged**
