### PR TITLE
Minor fixes and stuff

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
This fixes multiple minor issues and implements some enhancements, see the commit descriptions for issues fixed.

### CODE REVIEW

**Comment by NillerMedDild** [comment]
Looks good! Got anything else you'd like to add while you're at it, or can I merge? :)

**Comment by MaxNeedsSnacks** [comment]
Hmm, still thinking about Chem Reactor recipes, but I'm probs gonna add that to its own branch / PR.

Should be ready to merge^^

**Comment by NillerMedDild** [comment]
Sweet!

**Comment by NillerMedDild** [comment]
Worth a shot :P

**Comment by MaxNeedsSnacks** [comment]
rip.

i could just PR to e2es and see what that does lol

**Pull request merged**
