### PR TITLE
Extended updates. "Process".

### PR DESCRIPTION
**Pull request by Krutoy242**
Bunch of fixes and improvments, which i did for my E2E addon, but want to suggest to origin. Most of them already approved by @NillerMedDild , but some still need review.
Follow Commit Subject for description.

Several important changes in screenshots:

Wood rework. Now all machines can saw all wood logs, scalled by machine Tier

Myrmex resin recycle 

Return of Quark chests

Filling ThermExp Ducts in with other methods

 
More types of fuels for AdvGen Gas Generator

New two veins for ImrEng Excavator - Osmium and NC ore

More Adv.Rock. recipes. Grow AstSor crystals in crystallizer

More Cat's balls of fur drops with tooltip like UU-Matter.

 More items in IC2 Scrap Boxes. Most common would be matter balls

Cheaper Wireless RF from ExUtil2

Harder Omni-Connectors for Integrated Dynamics

Use rock crusher to obtain some resources from Twilight Forest blocks

More coolants for Thermal Mediator

Clear Tanks and Reserviors keeping their enchants and levels

EnderIO liquids made in AdvRocketry Chemical Reactor.
https://imgur.com/eaP8GpM

### CODE REVIEW

**Comment by theboo** [comment]
I'm assuming it doesn't use the one in the recipe? Although idk why you would have an extra one in the first place?

**Comment by NillerMedDild** [comment]
The 3x Omnidirectional Connector craft is for copying them so they have the same ID iirc :)

**Comment by Krutoy242** [comment]
> The x3 craft worries me, due to how I think Omnidirectional Connectors work. They are often given an ID to match when crafted, and I have a slight feeling it may not end well with 3 of them?

Tested in game. They got channel of connector used in craft.

**Comment by MorganSimic** [comment]
I just had an idea. What about implementing a chisel option for chests and make quark chests available that way. Beacuse i always liked the fact that those chests were gone, they annoyed me. But i get that some people would like them for decorational purposes. With a chisel option (assuming that works, but looking at FTB:I it should) chest crafts would still always give vanilla chests and quark chests are available.

**Comment by MorganSimic** [comment]
And i think recylcing Aurora blocks into cyanide is way to progression breaking. It's so easy to get massive amounts of aurora blocks and never need any cyanide again. In general, while a neat idea for me personal it has the feeling of feature creep to it.
In general i would be really careful with recyling recipes as they have a tendency to cause unexpected loops if not careful.

**Comment by Krutoy242** [comment]
> What about implementing a chisel option for chests and make quark chests available that way. 
> they annoyed me.

Why chests would annoy anyone? They just there, you can always craft vanilla chests. But I like chisel idea. It would be nice to have both ways.

> recylcing Aurora blocks into cyanide is way to progression breaking.

No, its not. For many reasons
1. Cyanide is easier to obtain then its looks like. Basically, its just processed uranium in reactor. NC reactor can process it too. 
2. Rock crusher is NC machine too. So, if you want to recycle Aurora blocks, you need same machines Tier as Fission Reactor
3. Aurora is not that easy to obtain. You need to spend hour or two, if you want to advance progression to last chapter.
4. There is only 10% chance to get cyanide from Aurora and doubled energy consumption (12 000 RF/t). 

Well, good you didnt know that Castle Blocks provide Calcium Sulfate =))

**Comment by MorganSimic** [comment]
Quark chests annoy me because when i want to craft a chest, i almost always want a vanilla chest. But if i don't have oak wood on hand and use something else, i get a Quark chest, wich i don't want and need extra steps to convert them to a vanilla chest. That's why i'm glad they are gone. The chisel option would remove the annoyance of the craft but everyone who wants them for decorational purposes can easily get them.

As for the recylcing of Twilight Forest stuff, i feel to many people would forgo the automation and just veinmine a TF building, recyle it and be happy. I'm aware this could be a way to make TF more useful, as it is pretty useless and almost obsolote but this a pack all about automtion and this provides a too easy option to not automate stuff. Especially Calcium Sulfate. I feel there should not be an alternative for that, as the processing chain is really cool to automate.

One additional thing, while i understand making the igniter a bit more expensive, dragon blood is just way over the top and really doesn't fit the function of the block. I personally wouldn't change it at all but the steel i can get behind, the dragon blood not.

As a closing note, i sound so negative towards these changes but this only for those particular few. The rest is extremely awesome, you are truly a craft tweaker god, this work is amazing. Thank you!

**Comment by Krutoy242** [comment]
> you are truly a craft tweaker god, this work is amazing

Thank you for mention this, i was starting to think you are only to crititize.

> i almost always want a vanilla chest.

When? I almost always want `<ore:chest>`, not a vanilla one. I can't believe you use exactly vanilla chests for decorative purpose.
Oh, there is a little thing. Custom hopper recipe have `<minecraft:chest>` instead of `ore` one. But this not Quark's chest problem. 

> would forgo the automation and just veinmine a TF building

What "automation" Cyanite needs? I believe there is no automation at all. You just throw uranium into any reactor. Is it big loss if you same way throw Aurora blocks into rock crusher instead?
Same time, progress to the Queen in TF take you more time. If you even didnt start NC yet (considering you cant throw uranium in reactor), you have no decent armor or weapon to progress through TF. Even if you managed to finish TF before NC, what next? There is no practival use for Cyanite anyway on this game stage.

> Especially Calcium Sulfate. I feel there should not be an alternative for that, as the processing chain is really cool to automate.

Recycling not disable need of automating. You need >10 000 of Calcium Sulfate to finish modpack. To obtain this amount you should recycle >100 000 blocks of Castle Rune Brick. This runes is not common. One castle contain about 1000 - 2000 of them, spread over complex.



> understand making the igniter a bit more expensive, dragon blood is just way over the top and really doesn't fit the function of the block

My opinion - if something is infinite, it should cost 10 times more. We both like automation - there is lot of fun ways to automate igniting bedrock. Igniter disable them all. And when you actually need grains of infinity, you already can defeat one poor fire dragon, if you want "easy" way.

**Comment by Krutoy242** [comment]
With further investigation through E2E issues i found that i still made few mistakes with Forestry circuits. I would fix them in new commit in several days. If you planned to merge changes soon, let me know and i will do this faster.

**Comment by NillerMedDild** [comment]
I do not plan to merge this soon I'm afraid, some RL stuff is keeping me very very busy.

**Review by NillerMedDild — APPROVED** [review]
Looks good to me, I've fixed the Forestry chipset tag issues during merge-conflict resolution, so it should be good to go \o/

Merging and testing locally.

**Comment by NillerMedDild** [comment]
Would you mind writing a short changelog for all these changes? :) Changelogs for bug fixes with open issues not needed.

**Comment by Krutoy242** [comment]
> Would you mind writing a short changelog for all these changes? :) Changelogs for bug fixes with open issues not needed.

Yes, I can. How much time I have? (right now I'm already in bed going to sleep)

> I've fixed the Forestry chipset tag issues

Uh, seems like I missed moment to do it myself... Sorry, I promised to do it in "several days".
Seems like the "actual" fix would be in next PR. This time i would test it several times.

**Comment by NillerMedDild** [comment]
You have the time you need :)

You did fix the chipset tags, I just missed it: https://github.com/NillerMedDild/Enigmatica2Expert/pull/1773/commits/36ffbe2bcdd624c1949b4e08baf4dd7213348305

**Pull request merged**
